### ISSUE TITLE
Installation through Package Control provides incorrect code

### ISSUE THREAD

**Issue by alexwidener** [karelvuong/st-fox#19]
{
    "theme": "fox.dark.sublime-theme",
    "color_scheme": "Packages/Theme - Fox/fox.dark.tmTheme"
}
is what is provided  in the tab that pops up when it should be 

{
  "theme": "Fox.sublime-theme",
  "color_scheme": "Packages/Theme - Fox/fox.dark.tmTheme"
}

Otherwise, the UI breaks.

**Comment by karelvuong** [comment]
Thanks for reporting this, @alexwidener. 

Sorry it took so long to get back to you on this. This issue (and others) have been fixed in the latest release v1.1.11. :smile:
