### ISSUE TITLE
Find/Replace chopped off

### ISSUE THREAD

**Issue by aubreypwd** [karelvuong/st-fox#22]
![](https://cloudup.com/cCsT8PYvPHB+?raw.png)

The "Replace" section is chopped off.

**Comment by buildersbrewery** [comment]
see equinusocio/material-theme#67

**Comment by buildersbrewery** [comment]
This is a `Sublime Text` bug, not a theme bug.

**Comment by aubreypwd** [comment]
"Resize the panel by dragging the top edge..."

Worked for me.

**Comment by buildersbrewery** [comment]
https://cloud.githubusercontent.com/assets/474329/8178894/a0dd09c0-1412-11e5-8ecf-f7f9ade439ae.gif

for future visitors to this issue
